name: call generate readme from json

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    uses: devinschumacher/workflows/.github/workflows/generate-readme-from-json.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
